---
# tasks/main.yml - Instalar y configurar Traefik y Portainer
- name: Include preparation tasks
  ansible.builtin.include_tasks: prepare.yml

- name: Include installation tasks
  ansible.builtin.include_tasks: install.yml
