---
# tasks/main.yml - Instalar y configurar Traefik y Portainer
- name: Include preparation tasks
  ansible.builtin.import_tasks: prepare.yml
  tags: [traefik, portainer]

- name: Include installation tasks
  ansible.builtin.import_tasks: install.yml
  tags: [traefik, portainer]
