---
- name: Include Docker repository task
  ansible.builtin.import_tasks: repo.yml
  tags: [docker, docker-repo]

- name: Include Docker installation task
  ansible.builtin.import_tasks: install.yml
  tags: [docker, docker-install]

- name: Include Docker daemon configuration task
  ansible.builtin.import_tasks: daemon.yml
  tags: [docker, docker-daemon]
