---
- name: Include Docker repository task
  ansible.builtin.include_tasks: repo.yml

- name: Include Docker installation task
  ansible.builtin.include_tasks: install.yml

- name: Include Docker daemon configuration task
  ansible.builtin.include_tasks: daemon.yml
