name: Shell lint

on: [push, pull_request]

jobs:
  lint-shell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: ShellCheck
        uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # 2.0.0
        with:
          scandir: '.'
          additional_files: 'main.sh'
          ignore_paths: 'ansible'

      - name: Setup shfmt
        uses: mfinelli/setup-shfmt@e52fd78d3a9a28dcf46656d4729c5d76be40ac0e # v4.0.1
        with:
          shfmt-version: '3.7.0'

      - name: shfmt check
        run: shfmt -d -s -i 2 modules/*.sh main.sh
